import nodemailer from "nodemailer";
import Property from "../models/PropertyModel.js";

// @desc    Send an inquiry email notification directly to the listing agent
// @route   POST /api/properties/:id/contact
// @access  Public
export const contactAgent = async (req, res) => {
  try {
    const { name, email, message } = req.body;
    const propertyId = req.params.id;

    if (!name || !email || !message) {
      return res.status(400).json({ message: "Please complete all empty form fields." });
    }

    const property = await Property.findById(propertyId).populate("owner", "name email");

    if (!property) {
      return res.status(404).json({ message: "The requested property was not found." });
    }

    const agentEmail = property.owner?.email || "brokerage.estate.ease@gmail.com";
    const agentName = property.owner?.name || "Estate Ease Broker";

    // ⚡ CONFIGURE THE SMTP TRANSPORTER ENGINE (Uses Mailtrap or Ethereal for testing; replace with your real Gmail later)
    const transporter = nodemailer.createTransport({
      host: "sandbox.smtp.mailtrap.io", // 👈 Replace with ://gmail.com for real production
      port: 2525,                       // 👈 Replace with 465 (secure) or 587 for real production
      auth: {
        user: process.env.EMAIL_USER || "your_mock_user_id", 
        pass: process.env.EMAIL_PASS || "your_mock_password",
      },
    });

    // Custom Styled HTML Email Template Payload
    const mailOptions = {
      from: `"Estate Ease Marketplace" <no-reply@estateease.com>`,
      to: agentEmail,
      subject: `🔥 New Client Property Inquiry: ${property.title}`,
      html: `
        <div style="font-family: sans-serif; padding: 20px; color: #333; max-width: 600px; border: 1px solid #eee; rounded: 12px;">
          <h2 style="color: #2563eb;">New Lead Notification</h2>
          <p>Hello <strong>${agentName}</strong>,</p>
          <p>A client is highly interested in your listing: <a href="http://localhost:5173/properties/${property._id}" style="color: #2563eb; font-weight: bold;">${property.title}</a></p>
          
          <div style="background-color: #f9fafb; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin-top: 0; color: #111827; font-size: 14px; text-transform: uppercase;">Lead Contact Details</h3>
            <p style="margin: 5px 0; font-size: 14px;"><strong>Name:</strong> ${name}</p>
            <p style="margin: 5px 0; font-size: 14px;"><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>
            <p style="margin: 15px 0 5px 0; font-size: 14px;"><strong>Client Message:</strong></p>
            <p style="margin: 0; font-size: 14px; color: #4b5563; font-style: italic; border-left: 3px solid #cbd5e1; padding-left: 10px;">"${message}"</p>
          </div>
          
          <p style="font-size: 12px; color: #9ca3af; margin-top: 30px; border-t: 1px solid #eee; pt: 10px;">This automated lead notification message was generated by Estate Ease Real Estate Engine.</p>
        </div>
      `,
    };

    await transporter.sendMail(mailOptions);

    res.json({ message: "Inquiry dispatch successful! The listing agent has been notified via email." });
  } catch (error) {
    console.error("NODEMAILER INQUIRY PIPELINE CRASH:", error);
    res.status(500).json({ message: `Mail server configuration issue: ${error.message}` });
  }
};
